# Generated by Django 4.2.6 on 2023-10-23 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_photo_categoria_alter_photo_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
    ]
