# Generated by Django 4.2.6 on 2023-10-23 03:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_photo_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='data_photo',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
