# Generated by Django 4.2.6 on 2023-10-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0005_alter_photo_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='categoria',
            field=models.CharField(choices=[('Nebulosa', 'NEBULOSA'), ('Estrela', 'ESTRELA'), ('Galáxia', 'GALÁXIA'), ('Planeta', 'PLANETA')], default='', max_length=100),
        ),
    ]
