# Generated by Django 4.2.6 on 2023-10-24 16:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0008_remove_photo_data_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='data_photo',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
